services:
  - type: web
    name: restaurant-review-nlp
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyBacT2fdKvU1KUrtDyRBGQDxQuXyiyFxYg
